services:
    frontend:
        restart: unless-stopped
        ports:
            - "80:80"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M

    spring-boot:
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 768M

    mongodb:
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 1G