services:
    frontend:
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
            - ./docker/nginx/ssl:/etc/nginx/ssl:ro
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 256M

    spring-boot:
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 768M

    mongodb:
        restart: unless-stopped
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: 1G