services:
    frontend:
        image: ${DOCKER_REGISTRY_IP}/pharmacy_frontend:${FRONTEND_IMAGE_TAG}
        container_name: pharmacy-frontend

    spring-boot:
        image: ${DOCKER_REGISTRY_IP}/pharmacy_backend:${SPRING_BOOT_IMAGE_TAG}
        container_name: pharmacy-backend

    mongodb: 
        image: mongo:8  
        container_name: pharmacy-mongo