# MongoDB configuration
spring.mongodb.database=${MONGODB_DATABASE:pharmacy}
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/pharmacy}

# JWT configuration
jwt.secret=cfe0f76e14af65766fb6c53578efc4bc0aeb0a98599cccabc3f401750cbaff4c

# Port and context path configuration
server.port=${SERVER_PORT:8081}
