spring.application.name=pharmacy-project
spring.mongodb.uri=${MONGODB_URI:mongodb://mongodb:27017/pharmacy}
spring.mongodb.database=${MONGODB_DATABASE:pharmacy}
jwt.signer.key=cfe0f76e14af65766fb6c53578efc4bc0aeb0a98599cccabc3f401750cbaff4c
server.servlet.context-path=/api
server.port=${SERVER_PORT:8081}