# Name of the application
spring.application.name=pharmacy-project

# Port and context path configuration
server.servlet.context-path=/api

# Health check configuration
management.endpoint.health.show-details=always
management.health.mongodb.enabled=true

# profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}