# MongoDB configuration
spring.mongodb.database=${MONGODB_DATABASE:pharmacy}

# JWT configuration
spring.config.import=optional:configtree:/run/secrets/

# Secret
jwt.secret=${jwt}
spring.mongodb.uri=${mongo_uri}

# Port and context path configuration
server.port=${SERVER_PORT:8081}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always